"""added fields for email confirmation after registration

Revision ID: 01eeecca2a3b
Revises: 782fc4a79a31
Create Date: 2020-12-03 09:10:10.660731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01eeecca2a3b'
down_revision = '782fc4a79a31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confirmed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('confirmed')

    # ### end Alembic commands ###
