"""adding avatars

Revision ID: 311a518514cb
Revises: d23024cdb10c
Create Date: 2020-11-12 09:50:32.075385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '311a518514cb'
down_revision = 'd23024cdb10c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_l', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('avatar_m', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('avatar_s', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('avatar_s')
        batch_op.drop_column('avatar_m')
        batch_op.drop_column('avatar_l')

    # ### end Alembic commands ###
