"""adding likes 1

Revision ID: 32273eca9d85
Revises: 4553e4b842b9
Create Date: 2020-11-25 17:20:18.706818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32273eca9d85'
down_revision = '4553e4b842b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe_like',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipe_like')
    # ### end Alembic commands ###
