"""adding likes

Revision ID: 43114b7493a8
Revises: d7db9181981b
Create Date: 2020-11-25 17:01:29.493807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43114b7493a8'
down_revision = 'd7db9181981b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe_like',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['recipe.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipe_like')
    # ### end Alembic commands ###
