"""changes on comments

Revision ID: 469914b27a4f
Revises: 1359f424b8dc
Create Date: 2020-11-29 12:24:39.093540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '469914b27a4f'
down_revision = '1359f424b8dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('commented_on_recipe_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'recipe', ['commented_on_recipe_id'], ['id'])
        batch_op.drop_column('recipe_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipe_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'recipe', ['recipe_id'], ['id'])
        batch_op.drop_column('commented_on_recipe_id')

    # ### end Alembic commands ###
