"""telephones removed

Revision ID: 5859f8da6b96
Revises: c255fe70bae0
Create Date: 2020-11-11 10:51:50.928129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5859f8da6b96'
down_revision = 'c255fe70bae0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('telephone')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telephone',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('country_code', sa.INTEGER(), nullable=True),
    sa.Column('area_code', sa.INTEGER(), nullable=True),
    sa.Column('number', sa.VARCHAR(length=15), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
