"""added categories and tags to the recipe model

Revision ID: 63bf3dba1858
Revises: c40bf1a060c8
Create Date: 2020-11-24 18:04:29.287550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63bf3dba1858'
down_revision = 'c40bf1a060c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cate', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('tags', sa.PickleType(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.drop_column('tags')
        batch_op.drop_column('cate')

    # ### end Alembic commands ###
