"""adding telephones

Revision ID: 66d39d3c9ac4
Revises: e600ea4bb9c2
Create Date: 2020-11-10 15:54:45.751675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66d39d3c9ac4'
down_revision = 'e600ea4bb9c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telephones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=True),
    sa.Column('country_code', sa.Integer(), nullable=True),
    sa.Column('area_code', sa.Integer(), nullable=True),
    sa.Column('number', sa.String(length=15), nullable=True),
    sa.ForeignKeyConstraint(['race_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('telephones')
    # ### end Alembic commands ###
