"""adding timestamp to likes, cascade delete

Revision ID: 782fc4a79a31
Revises: b78ffcfed9a7
Create Date: 2020-12-02 08:35:52.279260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '782fc4a79a31'
down_revision = 'b78ffcfed9a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe_like', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_recipe_like_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe_like', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recipe_like_timestamp'))
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
