"""recipes adding fields

Revision ID: 8a462aeb65b2
Revises: 918fa7eb8a1a
Create Date: 2020-11-11 15:26:43.374117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a462aeb65b2'
down_revision = '918fa7eb8a1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'body')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('body', sa.VARCHAR(length=140), nullable=True))
    # ### end Alembic commands ###
