"""recipes adding fields

Revision ID: 918fa7eb8a1a
Revises: c417d58f2cc2
Create Date: 2020-11-11 15:25:14.777915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '918fa7eb8a1a'
down_revision = 'c417d58f2cc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'body')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('body', sa.VARCHAR(length=140), nullable=True))
    # ### end Alembic commands ###
