"""empty message

Revision ID: c255fe70bae0
Revises: 6267d53362e4
Create Date: 2020-11-10 16:21:28.464898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c255fe70bae0'
down_revision = '6267d53362e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telephone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('country_code', sa.Integer(), nullable=True),
    sa.Column('area_code', sa.Integer(), nullable=True),
    sa.Column('number', sa.String(length=15), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('telephones')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telephones',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('country_code', sa.INTEGER(), nullable=True),
    sa.Column('area_code', sa.INTEGER(), nullable=True),
    sa.Column('number', sa.VARCHAR(length=15), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('telephone')
    # ### end Alembic commands ###
