"""adding images and approved field to recipes

Revision ID: c40bf1a060c8
Revises: 311a518514cb
Create Date: 2020-11-21 11:50:44.727391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c40bf1a060c8'
down_revision = '311a518514cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approved', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('imag', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.drop_column('imag')
        batch_op.drop_column('approved')

    # ### end Alembic commands ###
