"""recipes adding fields

Revision ID: c417d58f2cc2
Revises: 8e37e0d5d19e
Create Date: 2020-11-11 15:24:01.278495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c417d58f2cc2'
down_revision = '8e37e0d5d19e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('desc', sa.String(length=500), nullable=True))
    op.add_column('recipe', sa.Column('ingr', sa.String(length=500), nullable=True))
    op.add_column('recipe', sa.Column('name', sa.String(length=140), nullable=True))
    op.add_column('recipe', sa.Column('stps', sa.String(length=1500), nullable=True))
    op.drop_column('recipe', 'body')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('body', sa.VARCHAR(length=140), nullable=True))
    op.drop_column('recipe', 'stps')
    op.drop_column('recipe', 'name')
    op.drop_column('recipe', 'ingr')
    op.drop_column('recipe', 'desc')
    # ### end Alembic commands ###
