"""renaming columns

Revision ID: d7db9181981b
Revises: 8e134478022a
Create Date: 2020-11-25 14:00:17.088610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7db9181981b'
down_revision = '8e134478022a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('description', sa.String(length=2000), nullable=True))
        batch_op.add_column(sa.Column('image', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('ingredients', sa.String(length=2500), nullable=True))
        batch_op.add_column(sa.Column('serves', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('steps', sa.String(length=5000), nullable=True))
        batch_op.drop_column('serv')
        batch_op.drop_column('cate')
        batch_op.drop_column('stps')
        batch_op.drop_column('desc')
        batch_op.drop_column('imag')
        batch_op.drop_column('ingr')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ingr', sa.VARCHAR(length=500), nullable=True))
        batch_op.add_column(sa.Column('imag', sa.VARCHAR(length=64), nullable=True))
        batch_op.add_column(sa.Column('desc', sa.VARCHAR(length=500), nullable=True))
        batch_op.add_column(sa.Column('stps', sa.VARCHAR(length=1500), nullable=True))
        batch_op.add_column(sa.Column('cate', sa.VARCHAR(length=32), nullable=True))
        batch_op.add_column(sa.Column('serv', sa.INTEGER(), nullable=True))
        batch_op.drop_column('steps')
        batch_op.drop_column('serves')
        batch_op.drop_column('ingredients')
        batch_op.drop_column('image')
        batch_op.drop_column('description')
        batch_op.drop_column('category')

    # ### end Alembic commands ###
